### PR TITLE
Remove kettle.properties when sourcing vars

### PR DESCRIPTION
**Pull request by JanKanis**
kettle.properties caches database hostnames and credentials, which is very annoying because that overrides changed vars settings. To prevent
more wasted time, remove them automatically when the vars file is sourced.

### CODE REVIEW

**Comment by cataphract** [comment]
I thought kettle.properties depended on `vars`. Do you have a `vars` file with a different name?

**Comment by JanKanis** [comment]
kettle.properties is generated from vars, but if vars is changed and sourced again, kettle.properties is not updated if it already exists

**Comment by cataphract** [comment]
What I mean is this: https://github.com/transmart/transmart-data/blob/master/samples/common/makefile.inc#L48

kettle.properties depends on vars

**Comment by JanKanis** [comment]
I often use vars files with different names for different environments/remote servers/etc, and some of the data people do too. It is very unexpected that one of the build rules would depend on a particular vars file rather than on the variables it defines. In that case my patch doesn't make a lot of sense, preferably make should depend on the variable values themselves, but I can't find how to do that just yet. Or else it should generate the file unconditionally.

**Comment by cataphract** [comment]
I'm fine with either generating the file unconditionally or having some pattern for the vars files.

**Comment by JanKanis** [comment]
I'm not sure how "some pattern for the vars file" would work. If I have `vars.foo` and `vars.bar` that define configs for different databases I may just source one or the other when I'm working on either one, without actually changing either of them. 

In my latest commit sourcing a vars file touches a vars_timestamp file on which the make rules depend.  It crossed your previous comment; it is still a side effect on sourcing a vars, but what do you think of this?

**Comment by cataphract** [comment]
Sorry, I think this is too disruptive. It will require replacement of all the vars files. In our case, it will require changing the puppet scripts, for other people, who knows.

**Comment by JanKanis** [comment]
Ok, I'll have a look at unconditionally generating those files then.

**Comment by JanKanis** [comment]
@cataphract Did you have a look at this already?

**Comment by cataphract** [comment]
Looks fine. Squash the commits and I'll merge.

**Comment by JanKanis** [comment]
@cataphract squashed and rebased, please merge

**Pull request merged**
