### PR TITLE
Additional configuration for datasource that allows transmart to recover the database connection if it was lost.

### PR DESCRIPTION
**Pull request by dennyverbeeck**
Additional configuration for datasource that allows transmart to recover the database connection if it was lost. This can happen for any number of reasons, e.g. postgres gets updated by auto-update.

### CODE REVIEW

**Comment by cataphract** [comment]
The query doesn't look right for Oracle.

**Comment by dennyverbeeck** [comment]
Indeed, changed the query.

**Comment by dennyverbeeck** [comment]
Also added a change in Config.groovy template to use the user.home system property rather than HOME environment variable as some OSes not set this (looking at you Windows).. user.home successfully tested on Windows and Ubuntu. Any news on the validation query for Oracle? I do not have access to an Oracle Db to test this, but it should be ok.

**Comment by JanKanis** [comment]
Oracle doesn't allow you to select something out of thin air. The Oracle version would be "select 1 from dual", where dual is a fake table that Oracle knows about. But postgres doesn't recognize that. And Oracle also has different syntax for 'limit', so that's not portable either. I was trying to think of a portable dummy query but I can't quickly think of one that does not return a potentially big result set.

**Comment by dennyverbeeck** [comment]
In the latest commit different validation queries are generated based on the database type

**Comment by dennyverbeeck** [comment]
Added: Fix for metabolomics issue that prevented non-integer intensities from being loaded correctly

**Pull request merged**
