### PR TITLE
fixed wrong schema qualification in concept_domain insert trigger

### PR DESCRIPTION
**Pull request by j-hudecek**
CONCEPT_ID sequence doesn't exist in tm_cz but i2b2_demodata

### CODE REVIEW

**Comment by cataphract** [comment]
Is this trigger (and its associated sequence) even needed? Because

* I don't see this trigger on Oracle and
* I looked at transmart-batch which I built based on the stored procedures/functions, and sequence used for generating values for `concept_cd` is `i2b2metadata.i2b2_id_seq`.

**Comment by j-hudecek** [comment]
It's defined as insert for concept_dimension 
CREATE TRIGGER trg_concept_dimension_cd
  BEFORE INSERT
  ON i2b2demodata.concept_dimension
  FOR EACH ROW
  EXECUTE PROCEDURE i2b2demodata.tf_trg_concept_dimension_cd();

**Comment by j-hudecek** [comment]
Perhaps it should be rewritten to use the correct sequence then

**Comment by cataphract** [comment]
That's for postgres, I meant oracle. But I see it's in `ddl/oracle/i2b2demodata/_cross.sql`:

	CREATE OR REPLACE TRIGGER "I2B2DEMODATA"."TRG_CONCEPT_DIMENSION_CD" 
		 before insert on "CONCEPT_DIMENSION"
		 for each row begin
		 if inserting then
		 if :NEW."CONCEPT_CD" is null then
		 select TM_CZ.CONCEPT_ID.nextval into :NEW."CONCEPT_CD" from dual;
		 end if;
		 end if;
		 end;

	/
	ALTER TRIGGER "I2B2DEMODATA"."TRG_CONCEPT_DIMENSION_CD" ENABLE;

So the same problem exists for Oracle. In fact:

    glopes ~/repos/transmart-upstream/transmart-data ((c316e33...)) $ git grep -i CONCEPT_ID | grep 'Type: SEQUENCE'
    ddl/oracle/i2b2demodata/_misc.sql:-- Type: SEQUENCE; Owner: I2B2DEMODATA; Name: CONCEPT_ID
    ddl/postgres/i2b2demodata/concept_dimension.sql:-- Name: concept_id; Type: SEQUENCE; Schema: i2b2demodata; Owner: -

And indeed transmart-batch is wrong. I looked at the function again and it reads:

    insert into i2b2demodata.concept_dimension
        (concept_cd
        , ...
        )
        select nextval('i2b2demodata.concept_id')
        , ...

**Pull request merged**
