### PR TITLE
Default port Solr is running is 8983

### PR DESCRIPTION
**Pull request by cdejonge**
Related to issue FT-1191

### CODE REVIEW

**Comment by cataphract** [comment]
The default production setup is to run solr deployed alongside transmart on port 8080 (hence there is no way to install a service for solr in transmart-data like there is for Rserve). If this doesn't suit your setup, just override the default by creating a `Config-extra.php`. Changing the default will break existing scripts (e.g. transmart-images) that rely on the default, for no good reason.

**Comment by cdejonge** [comment]
Not sure I can follow your reasoning. TranSMART indeed runs on 8080 (tomcat). This makes it impossible for “solr" to also run on port 8080, right?
In the default setup described on: https://wiki.transmartfoundation.org/pages/viewpage.action?pageId=6619205
“solr" is started on port 8983.
I thought to reflect this in the “Config.groovy” file, so “transmart” knows where to find “solr”.



Van: Gustavo Lopes <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: transmart/transmart-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 12 January 2015 10:34
Aan: transmart/transmart-data <transmart-data@noreply.github.com<mailto:transmart-data@noreply.github.com>>
CC: Cees de Jonge <c.de.jonge@philips.com<mailto:c.de.jonge@philips.com>>
Onderwerp: Re: [transmart-data] Default port Solr is running is 8983 (#54)


The default production setup is to run solr deployed alongside transmart on port 8080 (hence there is no way to install a service for solr in transmart-data like there is for Rserve). If this doesn't suit your setup, just override the default by creating a Config-extra.php. Changing the default will break existing scripts (e.g. transmart-images) that rely on the default, for no good reason.

—
Reply to this email directly or view it on GitHub<https://github.com/transmart/transmart-data/pull/54#issuecomment-69545705>.browse.hide = true

________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by Terry-Weymouth** [comment]
Cees, the port for SOLR is already available (and set in Config.groovy in the "user configuration" file, the default location of which is ~/.grails/transmartConfig/Config.groovy. This file is initialized, in one of the make options, by transmart-data. In tern, transmart-date gets it's default information from the Config-extra.php file to which Gustavo is referring. Since tomcat runs (by default) on port 8080, and since changing this default would be messy and "dangerous" - another different default port needs to be chosen for SOLR. This is not too bad, since there is also a make option for SOLR with will install SOLR with that default in mind.

**Comment by cdejonge** [comment]
Terry,
I agree there.
I was not trying to change the port transmart is running on. I thought I was trying to tell transmart on which port SOLR was running (variable “solrPort” in Config-template.groovy).
“solrPort” is now default set to port 8080 (on which transmart is already running). So transmart is now (by default) thinking SOLR is running on port 8080, right? This cannot work, because transmart is running on that port, right?
I thought “solrPort” should be set to 8983, because transmart-data start SOLR at this port by default (make –C solr/ start).

Regards,
Cees

Van: Terry Weymouth <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: transmart/transmart-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 12 January 2015 12:26
Aan: transmart/transmart-data <transmart-data@noreply.github.com<mailto:transmart-data@noreply.github.com>>
CC: Cees de Jonge <c.de.jonge@philips.com<mailto:c.de.jonge@philips.com>>
Onderwerp: Re: [transmart-data] Default port Solr is running is 8983 (#54)


Cees, the port for SOLR is already available (and set in Config.groovy in the "user configuration" file, the default location of which is ~/.grails/transmartConfig/Config.groovy. This file is initialized, in one of the make options, by transmart-data. In tern, transmart-date gets it's default information from the Config-extra.php file to which Gustavo is referring. Since tomcat runs (by default) on port 8080, and since changing this default would be messy and "dangerous" - another different default port needs to be chosen for SOLR. This is not too bad, since there is also a make option for SOLR with will install SOLR with that default in mind.

—
Reply to this email directly or view it on GitHub<https://github.com/transmart/transmart-data/pull/54#issuecomment-69557126>.

________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by cataphract** [comment]
> Not sure I can follow your reasoning. TranSMART indeed runs on 8080 (tomcat). This makes it impossible for “solr" to also run on port 8080, right?

No, it doesn't. Application servers can run several applications simultaneously. See for instance: https://github.com/thehyve/transmart-images/blob/master/firstBoot.sh

**Comment by cdejonge** [comment]
OK, now I’ll get it. SOLR is started from within tomcat.
This is different then described in the indicated installation manual.
Thanks for the clarification and the example script.


Van: Gustavo Lopes <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: transmart/transmart-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 12 January 2015 13:05
Aan: transmart/transmart-data <transmart-data@noreply.github.com<mailto:transmart-data@noreply.github.com>>
CC: Cees de Jonge <c.de.jonge@philips.com<mailto:c.de.jonge@philips.com>>
Onderwerp: Re: [transmart-data] Default port Solr is running is 8983 (#54)


Not sure I can follow your reasoning. TranSMART indeed runs on 8080 (tomcat). This makes it impossible for “solr" to also run on port 8080, right?

No, it doesn't. Application servers can run several applications simultaneously. See for instance: https://github.com/thehyve/transmart-images/blob/master/firstBoot.sh

—
Reply to this email directly or view it on GitHub<https://github.com/transmart/transmart-data/pull/54#issuecomment-69560791>.

________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by Terry-Weymouth** [comment]
Oops, sorry that I got that backward. Yes, what you are suggesting sounds
right. Let me check. Terry.

From:  Cees de Jonge <notifications@github.com>
> I thought ³solrPort² should be set to 8983, because transmart-data start SOLR
> at this port by default (make ­C solr/ start).

**Comment by cdejonge** [comment]
Hoi Terry,

Gustavo explained thing perfectly. The difference is how SOLR is started. I started SOLR as a separate process (described in the installation description I used).
SOLR can also be started as part of tomcat (is much nicer I think). So we just have to adjust the installation description I think.



Van: Terry Weymouth <notifications@github.com<mailto:notifications@github.com>>
Beantwoorden - Aan: transmart/transmart-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 12 January 2015 14:09
Aan: transmart/transmart-data <transmart-data@noreply.github.com<mailto:transmart-data@noreply.github.com>>
CC: Cees de Jonge <c.de.jonge@philips.com<mailto:c.de.jonge@philips.com>>
Onderwerp: Re: [transmart-data] Default port Solr is running is 8983 (#54)

Oops, sorry that I got that backward. Yes, what you are suggesting sounds
right. Let me check. Terry.

From: Cees de Jonge <notifications@github.com<mailto:notifications@github.com>>
> I thought ³solrPort² should be set to 8983, because transmart-data start SOLR
> at this port by default (make ­C solr/ start).

—
Reply to this email directly or view it on GitHub<https://github.com/transmart/transmart-data/pull/54#issuecomment-69567077>.

________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by Terry-Weymouth** [comment]
Thanks all.

From:  Cees de Jonge <notifications@github.com>
> Gustavo explained thing perfectly. The difference is how SOLR is started. I
> started SOLR as a separate process (described in the installation description
> I used). 
> SOLR can also be started as part of tomcat (is much nicer I think). So we just
> have to adjust the installation description I think.

**Pull request closed without merging**
